server:
  error:
    include-message: always
  port: 8080

spring:
  application:
    name: book-server

  config:
    import: configserver:${CONFIG_SERVER_URI}

  cloud:
    config:
      fail-fast: true

  profiles:
    active: base, postgres, liquibase
