server:
  port: 8765

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations:
#            - /home/dmitry/java/projects/sandbox/microservices-example/config-server/configs
            - classpath:/configs

